admin_ext/urls.py
#coding=utf-8

from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('admin_ext',
    url(r'^$', 'views.home', name='admin_home'),

    url(r'^login$', 'views.login', name='admin_login'),
    url(r'^logout$', 'views.logout', name='admin_logout'),

    url(r'^search$', 'views.admin_book_search', name='admin_book_search'),

    url(r'^book/$', 'views.book_index', name='admin_book_home'),
    url(r'^book/list/$', 'views.book_list', name='admin_book_list'),
    url(r'^book/isbn-add/$', 'views.book_isbn_add', name='admin_book_isbn_add'),
    url(r'^book/create/$', 'views.book_create', name='admin_book_create'),
    url(r'^book/(?P<id>\d+)/edit/$', 'views.book_edit', name='admin_book_edit'),
    url(r'^book/set/$', 'views.book_set', name='admin_book_set'),
    url(r'^book/(?P<id>\d+)/change/cover/$', 'views.book_change_cover', name='admin_book_change_cover'),

    url(r'^order/$', 'views.order_index', name='admin_order_home'),
    url(r'^order/download/$', 'views.order_download', name='admin_order_download'),
    url(r'^order/buy/list/$', 'views.order_buy_list', name='admin_order_buy_list'),
    url(r'^order/buy/(?P<id>\d+)/edit/$', 'views.order_buy_edit', name='admin_order_buy_edit'),
    url(r'^order/buy/set/$', 'views.order_buy_set', name='admin_order_buy_set'),
    url(r'^order/buy/deal/delete/$', 'views.order_book_deal_delete', name='admin_order_book_deal_delete'),
    url(r'^order/buy/deal/(?P<id>\d+)/set/$', 'views.order_buy_detail_set', name='admin_order_buy_detail_set'),
    url(r'^order/sell/list/$', 'views.order_sell_list', name='admin_order_sell_list'),
    url(r'^order/sell/(?P<id>\d+)/edit/$', 'views.order_sell_edit', name='admin_order_sell_edit'),
    url(r'^order/sell/set/$', 'views.order_sell_set', name='admin_order_sell_set'),
    url(r'^order/pick/$', 'views.order_pick_list', name='admin_order_pick_list'),
    url(r'^order/pick/(?P<time_stamp>\d+)/$', 'views.order_pick_show', name='admin_order_pick_show'),
    url(r'^order/pick/finish/(?P<time_stamp>\d+)/$', 'views.order_pick_finish', name='admin_order_pick_finish'),
    url(r'^logistic/set/$', 'views.logistic_set', name='admin_logistic_set'),
    url(r'^logistic/add/$', 'views.logistic_add', name='admin_logistic_add'),
    url(r'^logistic/delete/$', 'views.logistic_delete', name='admin_logistic_delete'),
)

book/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('book.views',
    url(r'^(?P<book_id>\d+)/$', 'page_book', name='page_book'),
    url(r'^taxonomy/(?P<taxonomy_id>\d+)/$', 'page_taxonomy', name='page_taxonomy'),
)

book/models.py
#coding=utf-8

import os
import json

from django.db import models
from django.conf import settings
from django.contrib.contenttypes.models import *
from django.contrib.contenttypes.generic import *

from main.db_choices import *
from main.models import *
from main.utils import *

from utils import *

# Create your models here.

class Taxonomy(BaseModel):
    name = models.CharField(verbose_name=u"名称", max_length=30)
    type = models.SmallIntegerField(verbose_name=u"分类类型", choices=TAXONOMY_TYPE, default=1)
    weight = models.SmallIntegerField(verbose_name=u"权重", default=1)
    level = models.SmallIntegerField(verbose_name=u"级别", default=1)
    parent = models.ForeignKey('self', blank=True, null=True)

    class Meta:
        db_table = "taxonomy"
        verbose_name = u"分类"
        verbose_name_plural = u"分类"
        ordering = ['-weight']

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        level = 1
        instance = self
        while True:
            if instance.parent is None:
                break;
            else:
                instance = instance.parent
                level += 1
        self.level = level
        super(Taxonomy, self).save(*args, **kwargs)

    def get_children_id_list(self):
        children = Taxonomy.objects.filter(parent=self)
        res_id_list = list(children.values_list('id', flat=True))
        for t in children:
            res_id_list += t.get_children_id_list()
        return res_id_list

    def get_children(self, include_self=False):
        res_id_list = self.get_children_id_list()
        if include_self:
            res_id_list.append(self.id)
        res_id_list = list(set(res_id_list))
        return Taxonomy.objects.filter(id__in=res_id_list)


    def get_parent(self):
        res = list()
        t = self
        while t.parent:
            t = t.parent 
            res.append(t)
        return res

class TaxonomyIndex(BaseModel):
    taxonomy = models.ForeignKey(Taxonomy)
    content_type = models.ForeignKey(ContentType, related_name='taxonomy_indexes')
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __unicode__(self):
        return self.taxonomy.name

    class Meta:
        db_table = 'taxonomy_index'
        verbose_name = u'分类索引'
        verbose_name_plural = u'分类索引'
        unique_together = ('taxonomy', 'content_type', 'object_id')

class Book(BaseModel): 
    name = models.CharField(verbose_name=u"名称", max_length=100, db_index=True)
    subtitle = models.CharField(verbose_name=u"副标题", max_length=100, blank=True, null=True)
    author = models.CharField(verbose_name=u"作者", max_length=50, db_index=True)
    translator = models.CharField(verbose_name=u"译者", max_length=100, blank=True, db_index=True)
    isbn = models.CharField(verbose_name="ISBN", max_length=25, blank=True, null=True, db_index=True)
    press = models.CharField(verbose_name=u"出版社", max_length=100, db_index=True)
    publication_date = models.DateField(verbose_name=u"出版日期", blank=True, null=True)
    version = models.CharField(verbose_name=u"版本", max_length=50, blank=True, null=True)
    language = models.CharField(verbose_name=u"语言", choices=BOOK_LANGUAGE_CHOICES, max_length=10)
    page_number = models.PositiveIntegerField(verbose_name=u"页数", blank=True, null=True)
    size = models.CharField(verbose_name=u"开本", max_length=10, blank=True, null=True)
    binding = models.CharField(verbose_name=u"装帧", max_length=10, blank=True, null=True)
    description = models.TextField(verbose_name=u"描述", blank=True, help_text=u"包括新旧要求，笔记要求")
    image = models.TextField(verbose_name=u"图片", blank=True, null=True, default=json.dumps(dict()))
    recommend = models.TextField(verbose_name=u"书评", blank=True)
    price_ori = models.FloatField(verbose_name=u"原价", default=0)
    price_new = models.FloatField(verbose_name=u"二手书价", default=0)
    price_old = models.FloatField(verbose_name=u"二手书价", default=0)
    status = models.PositiveIntegerField(verbose_name=u"状态", choices=BOOK_STATUS_CHOICES, default=0)
    taxonomy = GenericRelation(TaxonomyIndex, verbose_name=u"分类", null=True, blank=True)
    created = models.DateTimeField(verbose_name=u'创造日期', auto_now_add=True)
    modified = models.DateTimeField(verbose_name=u'修改日期', auto_now=True)
    organization = GenericRelation("OrganizationIndex", null=True, blank=True)
    

    class Meta:
        db_table = "book"
        verbose_name = u"书本"
        verbose_name_plural = u"书本"
        ordering = ['id']

    def __unicode__(self):
        return self.name

    @property
    def image_dict(self):
        try:
            return json.loads(self.image)
        except:
            return dict()

    @image_dict.setter
    def image_dict(self, image_dict):
        if image_dict is None or not isinstance(image_dict, dict):
            image_dict = dict()
        self.image = json.dumps(image_dict)

    @property
    def taxonomy_list(self):
        try:
            list_taxonomy_id = self.taxonomy.all().values_list('taxonomy__id', flat=True)
            res = Taxonomy.objects.filter(id__in=list_taxonomy_id)
            return res
        except:
            return Taxonomy.objects.none()

    @taxonomy_list.setter
    def taxonomy_list(self, taxonomy_list):
        ori_ts_ids = set(self.taxonomy_list.values_list('id', flat=True))
        ts_ids = set([ t.id for t in taxonomy_list ])
        same_ts_ids = ori_ts_ids & ts_ids
        self.taxonomy.filter(taxonomy__id__in=list(ori_ts_ids - same_ts_ids)).delete()
        for t_id in ts_ids - same_ts_ids:
            try:
                TaxonomyIndex(content_object=self, taxonomy=Taxonomy.objects.get(id=t_id)).save()
            except Exception, e:
                pass

    def save(self, *args, **kwargs):
        if self.price_old is None or self.price_old == 0:
            self.price_old = self.price_ori * settings.PRICE_ORI_NOW_RATE
        self.price_old = my_ceil(self.price_old)
        if self.description is None:
            self.description = ''
        self.description = self.description.strip()
        if not self.image_dict.has_key('cover'):
            tmp = self.image_dict
            tmp['cover'] = ''
            self.image_dict = tmp
        super(Book, self).save(*args, **kwargs)

    def get_taxonomy(self):
        list_taxonomy_id = self.taxonomy.all().values_list('taxonomy__id', flat=True)
        res = Taxonomy.objects.filter(id__in=list_taxonomy_id)
        return res

    def add_taxonomy(self, taxonomy):
        TaxonomyIndex(content_object=self, taxonomy=taxonomy).save()
        return self
    
    def add_taxonomies(self, taxonomies):
        for taxonomy in taxonomies:
            try:
                TaxonomyIndex(content_object=self, taxonomy=taxonomy).save()
            except:
                pass
        return self

    def get_logistic_info(self):
        try:
            from logistic.models import Logistic
            ls = Logistic.objects.filter(book=self)
        except Exception, e:
            self._logger.error(e)
            ls = Logistic.objects.none()
        return ls


class School(BaseModel):
    name = models.CharField(verbose_name=u"名称", max_length=50, unique=True)
    web = models.URLField(verbose_name=u"网址", blank=True, null=True)
    weight = models.SmallIntegerField(verbose_name=u"权重", default=1)
    region = models.CharField(verbose_name=u"地址", choices=REGION_CODE, max_length=50)
    ip_start = models.IPAddressField(verbose_name=u"IP起始地址", null=True, blank=True, )
    ip_end = models.IPAddressField(verbose_name=u"IP结束地址", null=True, blank=True, )

    class Meta:
        db_table = "school"
        verbose_name = u"学校"
        verbose_name_plural = u"学校"
        ordering = ['-weight']

    def __unicode__(self):
        return self.name

class Major(BaseModel):
    name = models.CharField(verbose_name=u"名称", max_length=50)
    type = models.SmallIntegerField(verbose_name=u"类型", default=0, choices=MAJOR_TYPE)
    diploma = models.SmallIntegerField(verbose_name=u"学历", default=0, choices=DIPLOMA)
    weight = models.SmallIntegerField(verbose_name=u"权重", default=1)

    class Meta:
        db_table = "major"
        verbose_name = u"院系"
        verbose_name_plural = u"院系" 
        unique_together = ('name', 'type', 'diploma')
        ordering = ['-weight']

    def __unicode__(self):
        return self.name

class Course(BaseModel):
    name = models.CharField(verbose_name=u"名称", max_length=50, unique=True)
    weight = models.SmallIntegerField(verbose_name=u"权重", default=1)

    class Meta:
        db_table = "course"
        verbose_name = u"课程"
        verbose_name_plural = u"课程" 
        ordering = ['-weight']

    def __unicode__(self):
        return self.name

class OrganizationIndex(BaseModel):
    school = models.ForeignKey('School', verbose_name=u"学校")
    major = models.ForeignKey('Major', verbose_name=u"院系")
    course = models.ForeignKey('Course', verbose_name=u"课程", null=True, blank=True)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        db_table = "school_course_index"
        verbose_name = u"所属组织索引"
        verbose_name_plural = u"所属组织索引"
        unique_together = ('school', 'major', 'course', 'content_type', 'object_id')

    def __unicode__(self):
        return self.school.name + '_' + self.major.name + '_' + self.course.name

admin_ext/forms.py
#coding=utf-8

import logging

from django.contrib import auth
from django.forms.util import *

from widgets import *

from book.utils import *
from main.forms import *
from utils import *

def get_taxonomy():
    from book.models import Taxonomy
    res = list()
    t1s = Taxonomy.objects.filter(level=1)
    for t1 in t1s:
        t2s = t1.get_children()
        tmp = [ (t.id, t.name) for t in t2s ]
        res.append((t1.name, tuple(tmp)))
    return tuple(res)

TAXONOMY = get_taxonomy()

class BasicAdminForm(BasicForm):

    def as_bs_horizontal_form(self):
        res = ''
        try: res += u'<div class="text-error" style="padding-left:50px;">' + str(self.errors['__all__']) + '</div><br>'
        except:
            pass
        for name, field in self.fields.items():
            if not isinstance(self.fields[name].widget, forms.HiddenInput):
                if self[name].errors:
                    res += u'<div class="control-group error">'
                else:
                    res += u'<div class="control-group">'
                res += str(self[name].label_tag(attrs={"class":"control-label"}))
                res += u'<div class="controls">'
                res += str(self[name])
                res += u'<span class="help-inline">' + str(self[name].errors.as_text()) + '</span>'
                res += u'<span class="help-block">' + str(self[name].help_text) + '</span>'
                res += u'</div>'
                res += u'</div>'
            else:
                res += str(self[name])
        return res

class AdminLoginForm(BasicAdminForm):
    username = forms.CharField(label=u"用户名", max_length=30, required=True)
    password = forms.CharField(label=u"密码", max_length=30, required=True, widget=forms.PasswordInput)
    callback = forms.CharField(label=u"Callback", max_length=100, required=False, widget=forms.HiddenInput)

    def clean(self):
        try:
            clean_data = super(AdminLoginForm, self).clean()
            if self.errors:
                raise Exception("Nothing")
            username = dict_get(clean_data, 'username')
            password = dict_get(clean_data, 'password')
            user = auth.authenticate(username=username, password=password)
            if user is not None and user.is_active and user.is_staff:
                clean_data['user'] = user
                return clean_data
            else:
                raise Exception("User illegal.")
        except Exception, e:
            raise forms.ValidationError("请输入正确的用户名密码。区分大小写。") 


class BookEditForm(BasicAdminForm):
    name = forms.CharField(label="书名", widget=forms.TextInput(attrs={"class":"input-xxlarge"}))
    subtitle = forms.CharField(label="副标题", widget=forms.TextInput(attrs={"class":"input-xxlarge"}), required=False)
    author = forms.CharField(label="作者")
    translator = forms.CharField(label="译者", required=False)
    isbn = forms.IntegerField(label="ISBN")
    press = forms.CharField(label="出版社")
    price_old = forms.FloatField(label="现价")
    price_ori = forms.FloatField(label="原价")
    status = forms.ChoiceField(
            label="状态", 
            widget=forms.Select(attrs={"class":"bs-select-deselect"}), 
            choices=BOOK_STATUS_CHOICES
            )
    publication_date = forms.DateTimeField(label="出版日期", widget=BSDateTimeInput, required=False)
    version = forms.CharField(label="版本", required=False)
    language = forms.ChoiceField(
            label="语言", 
            widget=forms.Select(attrs={"class":"bs-select-deselect"}), 
            choices=BOOK_LANGUAGE_CHOICES
            )
    page_number = forms.IntegerField(label="页数", required=False)
    size = forms.CharField(label="开本", required=False)
    binding = forms.CharField(label="装帧", required=False)

    taxonomy = forms.MultipleChoiceField(
            label="分类", 
            widget=forms.SelectMultiple(attrs={"class":"input-xxlarge bs-select"}), 
            choices=TAXONOMY, 
            required=False
            )

    description = forms.CharField(
            label=u"描述", 
            widget=forms.Textarea(attrs={"rows":10,"class":"input-xxlarge"}), 
            required=False
            )



class BookISBNAddForm(BasicAdminForm):
    isbn = forms.CharField(label=u"ISBN", max_length=30, required=True)

    def clean(self):
        clean_data = super(BookISBNAddForm, self).clean()
        if self.errors:
            return clean_data
        isbn = dict_get(clean_data, 'isbn')
        try:
            isbn = int(isbn)
            if isbn > 9999999999999 or isbn < 1000000000000:
                raise Exception('Nothing')
            clean_data['isbn'] = int(isbn)
        except:
            self.errors['isbn'] = ErrorList(["ISBN 必须是13 位数字!"])
        return clean_data

class OrderDownloadForm(BasicAdminForm):
    date = forms.DateField(label=u'日期', widget=BSDateInput, required=True)
    status_filterd = forms.BooleanField(label=u'仅未完成', required=False)

admin_ext/templates/admin_ext/page/book_index.jinja
{% extends "admin_ext/base/book_base.jinja" %}

{% block book_active_nav %}#book-nav-home{% endblock %}

{% block book_main %}
<div class="container">
    <div class="hero-unit">
        <h1>书本首页</h1>
        <p>酱油的。。。</p>
    </div>

</div>
{% endblock %}

admin_ext/templates/admin_ext/page/book_isbn_add.jinja
{% extends "admin_ext/base/book_base.jinja" %}

{% block book_active_nav %}#book-nav-isbn-add{% endblock %}

{% block book_main %}
<div class="container">
    <script type="text/javascript">
        $(function(){
                $('#id_position').focus();
        });
    </script>
    <form class="form-horizontal" method="post" action="{{ url('admin_book_isbn_add') }}">
    {% csrf_token %}
    {{ book_isbn_add_form.as_bs_horizontal_form() }}
    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-primary">提交</button>
        </div>
    </div>
    </form>
</div>
{% endblock %}

admin_ext/templates/admin_ext/page/index.jinja
{% extends "admin_ext/base/main.jinja" %}

{% block active_nav %}#nav-home{% endblock %}

{% block main %}
<div class="container">
    <div class="hero-unit">
        <h1>欢迎！</h1>
        <p>将来的后台首页。。。</p>
    </div>
</div>
{% endblock %}

admin_ext/templates/admin_ext/page/order_buy_edit.jinja
{% extends "admin_ext/base/order_base.jinja" %}

{% block order_active_nav %}#order-nav-buy{% endblock %}

{% block order_main %}
<div class="container">
    <legend><strong>{{ string('销售订单') }}</strong></legend>
    <div class="well well-small">
        {% from 'admin_ext/base/base_ctr.jinja' import key_value %}
        <div>
            {{ key_value('ID', order.id, 120, 200) }}
            {{ key_value('状态', order.get_status_display(), 120, 400) }}
        </div>
        <div>
            {{ key_value('电话', order.phone, 120, 200) }}
            {{ key_value('地址', order.address, 120, 400) }}
        </div>
        <div>
            {{ key_value('IP', order.ip, 120, 200) }}
            {{ key_value('提交时间', order.submitTime, 120, 400) }}
        </div>
        <div>
            {{ key_value('递送人员', order.deliverMan, 120, 200) }}
            {{ key_value('递送时间', order.deliverTime, 120, 400) }}
        </div>
        <div>
            {% if order.user %}
            {{ key_value('购买者', order.user, 120, 720) }}
            {% else %}
            {{ key_value('购买者', '匿名', 120, 720) }}
            {% endif %}
        </div>
        <div>
            {{ key_value('备注', order.remark, 120, 720) }}
        </div>
        <div>
            {{ key_value('备忘', order.resultRemark, 120, 720) }}
        </div>
    </div>
    <table id="tb-data" class="table table-striped table-hover">
        <tr>
            <th>ID</th>
            <th>书名</th>
            <th>作者</th>
            <th>版本</th>
            <th>ISBN</th>
            <th>现价</th>
            <th>原价</th>
            <th>买入价格</th>
            <th>成交价格</th>
            <th>状态</th>
            <th>数量</th>
            <th>购买类型</th>
            <th>库存</th>
            <th></th>
        </tr>
        {% for deal in order.get_book_deals() %}
        {% set book = deal.book %}
        {% set lgss = book.get_logistic_info() %}
        <tr>
            <td>{{ deal.id }}</td>
            <td>
                {% if book.status == 0 %}
                {{ book.name }}
                {% else %}
                <a href="{{ url('admin_book_edit', id=book.id) }}" target="_blank">{{ book.name }}</a>
                {% endif %}
            </td>
            <td>{{ book.author }}</td>
            <td>{{ book.version }}</td>
            <td>{{ book.isbn }}</td>
            <td>{{ book.price_old }}</td>
            <td>{{ book.price_ori }}</td>
            <td class="input-append">
                <input id="price-buy" value="{{ deal.price_buy }}" type="text" class="input-mini">
                <span class="add-on pointer" onClick="
                         $.get('{{ url('admin_order_buy_detail_set', id=deal.id ) }}', {'price-buy':$(this).parent().find('input#price-buy').val()},function(data, textStatus){ 
                             window.location.reload();
                         });
                    ">
                    <i class="icon-ok"></i>
                </span>
            </td>
            <td class="input-append">
                <input id="price-sell" value="{{ deal.price_sell }}" type="text" class="input-mini">
                <span class="add-on pointer" onClick="
                        $.get('{{ url('admin_order_buy_detail_set', id=deal.id ) }}', {'price-sell':$(this).parent().find('input#price-sell').val()},function(data, textStatus){ 
                            window.location.reload();
                        });
                    ">
                    <i class="icon-ok"></i>
                </span>
            </td>
            <td>{{ book.get_status_display() }}</td>
            <td>{{ deal.number }}</td>
            <td>{{ deal.get_type_display() }}</td>
            <td>
            {% for lgs in  lgss %}
                <span class="label label-info">
                    {{ string(lgs.position) }}
                </span>
            {% endfor %}
            </td>
            <td>
                <i class="icon-remove pointer" onClick="
                bootbox.confirm('确认删除？', function(result) {
                    if(result){
                        $.get('{{ url('admin_order_book_deal_delete') }}', {'id':{{ deal.id }}},function(data, textStatus){ 
                            window.location.reload();
                        });
                    }
                }); 
                "
                ></i>
            </td>
        </tr>
        {% if deal.url %}
        <tr>{{ deal.url }}</tr>
        {% endif %}
        {% endfor %}
        </div>
    </table>
    {% if order.status in [3, 4] %}
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="navbar-inner">
            <div class="container container-small">
                <div class="btn-toolbar pull-left">
                    <div class="btn-group btn-wrapper">
                        <span class="btn btn-danger" onclick="
                                $.get('{{ url('admin_order_buy_set') }}', {'id':{{ order.id }}, 'status':2},function(data, textStatus){ 
                                    window.location.reload();
                                });
                            ">{{ string('丢弃') }}</span>
                    </div>
                </div>
                <div class="btn-toolbar pull-right">
                    <div class="btn-group btn-wrapper dropup">
                        {% if order.status == 3 %}
                        <span class="btn btn-primary" onclick="
                                $.get('{{ url('admin_order_buy_set') }}', {'id':{{ order.id }}, 'status':4},function(data, textStatus){ 
                                    window.location.reload();
                                });
                                ">
                                {{ string('开始递送') }}
                        </span>
                        {% elif order.status == 4 %}
                        <span class="btn btn-primary" onclick="
                                $.get('{{ url('admin_order_buy_set') }}', {'id':{{ order.id }}, 'status':1},function(data, textStatus){ 
                                    window.location.reload();
                                });
                                ">
                                {{ string('完成') }}
                        </span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

admin_ext/templates/admin_ext/page/order_index.jinja
{% extends "admin_ext/base/order_base.jinja" %}

{% block order_active_nav %}#order-nav-home{% endblock %}

{% block order_main %}
<div class="container">
    <div class="hero-unit">
        <h1>订单首页</h1>
        <p>酱油的。。。</p>
    </div>

</div>
{% endblock %}

admin_ext/templates/admin_ext/page/order_sell_edit.jinja
{% extends "admin_ext/base/order_base.jinja" %}

{% block order_active_nav %}#order-nav-sell{% endblock %}

{% block order_main %}
<div class="container">
    <legend><strong>{{ string('销售订单') }}</strong></legend>
    <div class="well well-small">
        {% from 'admin_ext/base/base_ctr.jinja' import key_value %}
        <div>
            {{ key_value('ID', order.id, 120, 200) }}
            {{ key_value('状态', order.get_status_display(), 120, 400) }}
        </div>
        <div>
            {{ key_value('电话', order.phone, 120, 200) }}
            {{ key_value('地址', order.address, 120, 400) }}
        </div>
        <div>
            {{ key_value('IP', order.ip, 120, 200) }}
            {{ key_value('提交时间', order.submitTime, 120, 400) }}
        </div>
        <div>
            {{ key_value('递送人员', order.deliverMan, 120, 200) }}
            {{ key_value('递送时间', order.deliverTime, 120, 400) }}
        </div>
        <div>
            {% if order.user %}
            {{ key_value('购买者', order.user, 120, 720) }}
            {% else %}
            {{ key_value('购买者', '匿名', 120, 720) }}
            {% endif %}
        </div>
        <div>
            {{ key_value('备注', order.remark, 120, 720) }}
        </div>
        <div>
            {{ key_value('备忘', order.resultRemark, 120, 720) }}
        </div>
    </div>
    <table id="tb-data" class="table table-striped table-hover">
        <tr>
            <th>ID</th>
            <th>书名</th>
            <th>作者</th>
            <th>版本</th>
            <th>ISBN</th>
            <th>现价</th>
            <th>原价</th>
            <th>状态</th>
            <th>数量</th>
            <th>购买类型</th>
        </tr>
        {% for deal in order.get_book_deals() %}
        {% set book = deal.book %}
        <tr>
            <td>{{ deal.id }}</td>
            <td>
                {% if book.status == 0 %}
                {{ book.name }}
                {% else %}
                <a target="_blank" href="{{ out_link(string('shumaimai.cn/book/', book.id)) }}">{{ book.name }}</a>
                {% endif %}
            </td>
            <td>{{ book.author }}</td>
            <td>{{ book.version }}</td>
            <td>{{ book.isbn }}</td>
            <td>{{ book.price_old }}</td>
            <td>{{ book.price_ori }}</td>
            <td>{{ book.get_status_display() }}</td>
            <td>{{ deal.number }}</td>
            <td>{{ deal.get_type_display() }}</td>
        </tr>
        {% endfor %}
        </div>
    </table>
    {% if order.status in [3, 4] %}
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <div class="navbar-inner">
            <div class="container container-small">
                <div class="btn-toolbar pull-left">
                    <div class="btn-group btn-wrapper">
                        <span class="btn btn-danger" onclick="
                                $.get('{{ url('admin_order_buy_set') }}', {'id':{{ order.id }}, 'status':2},function(data, textStatus){ 
                                    window.location.reload();
                                });
                            ">{{ string('丢弃') }}</span>
                    </div>
                </div>
                <div class="btn-toolbar pull-right">
                    <div class="btn-group btn-wrapper dropup">
                        {% if order.status == 3 %}
                        <span class="btn btn-primary" onclick="
                                $.get('{{ url('admin_order_buy_set') }}', {'id':{{ order.id }}, 'status':4},function(data, textStatus){ 
                                    window.location.reload();
                                });
                                ">
                                {{ string('开始递送') }}
                        </span>
                        {% elif order.status == 4 %}
                        <span class="btn btn-primary" onclick="
                                $.get('{{ url('admin_order_buy_set') }}', {'id':{{ order.id }}, 'status':1},function(data, textStatus){ 
                                    window.location.reload();
                                });
                                ">
                                {{ string('完成') }}
                        </span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}